// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TopTenFilmList.Models;

#nullable disable

namespace ToDoList.Migrations
{
    [DbContext(typeof(TopTenFilmListContext))]
    partial class TopTenFilmListContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TopTenFilmList.Models.Actor", b =>
                {
                    b.Property<int>("ActorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ActorFName")
                        .HasColumnType("longtext");

                    b.Property<string>("ActorLName")
                        .HasColumnType("longtext");

                    b.Property<string>("ActorMainGenre")
                        .HasColumnType("longtext");

                    b.HasKey("ActorId");

                    b.ToTable("Actors");
                });

            modelBuilder.Entity("TopTenFilmList.Models.Film", b =>
                {
                    b.Property<int>("FilmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<float>("FilmAverageRating")
                        .HasColumnType("float");

                    b.Property<string>("FilmDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("FilmMPARating")
                        .HasColumnType("longtext");

                    b.Property<string>("FilmName")
                        .HasColumnType("longtext");

                    b.HasKey("FilmId");

                    b.ToTable("Films");
                });

            modelBuilder.Entity("TopTenFilmList.Models.FilmActor", b =>
                {
                    b.Property<int>("FilmActorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.HasKey("FilmActorId");

                    b.HasIndex("ActorId");

                    b.HasIndex("FilmId");

                    b.ToTable("FilmActors");
                });

            modelBuilder.Entity("TopTenFilmList.Models.FilmActor", b =>
                {
                    b.HasOne("TopTenFilmList.Models.Actor", "Actor")
                        .WithMany("JoinEntities")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TopTenFilmList.Models.Film", "Film")
                        .WithMany("JoinEntities")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Film");
                });

            modelBuilder.Entity("TopTenFilmList.Models.Actor", b =>
                {
                    b.Navigation("JoinEntities");
                });

            modelBuilder.Entity("TopTenFilmList.Models.Film", b =>
                {
                    b.Navigation("JoinEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
